apiVersion: apps/v1

kind: Deployment

metadata:

  name: webapp-deployment

  labels:

    app: mavenwebapp

spec:

  replicas: 3

  selector:

    matchLabels:

      app: mavenwebapp

  template:

    metadata:

      labels:

        app: mavenwebapp

    spec:

      containers:

      - name: mavenwebapp

        image: bharath/newrepo:5.0

        ports:

        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
 name: mavenwebappsvc
spec:
  type: NodePort
  selector:
   app: mavenwebapp
  ports:
   - port: 8081
     targetPort: 8080